### ISSUE TITLE
"cannot talk to GitHub"

### ISSUE THREAD

**Issue by shivamMg** [niemeyer/gopkg#63]
For some reason it cannot talk to GitHub. The requests time out. GH is up. Must be something between your server and GH.

![screenshot_20180911_141120](https://user-images.githubusercontent.com/7882752/45349484-02861700-b5cf-11e8-97d1-40c0d6bd58b9.png)

**Comment by niemeyer** [comment]
Right, GitHub is not accepting connections from gopkg.in right now. I'm in touch with support trying to figure out why and get it sorted.

**Comment by niemeyer** [comment]
As a side note, if you have a good contact at GitHub for that kind of issue, please raise attention so we can get it back up ASAP. If they take too long to respond I may end up switching IP addresses for a while so they can take their time to evaluate the issue, but I'd prefer to sort it the proper way instead.

**Comment by sysradium** [comment]
Unfortunately no :( Maybe switching IPs is a way to go now ...

**Comment by niemeyer** [comment]
We have a hot spare at https://p3.gopkg.in/yaml.v2 ready to switch. Let's give them another moment to evaluate the issue with the domain pointing to the right location, and if it takes too long we switch.

**Comment by niemeyer** [comment]
From GitHub:

> I'm speaking with our infrastructure teams and we've just updated our status while we work on this. I'll follow up with you as soon as we have an update.

**Comment by niemeyer** [comment]
Reflected in https://status.github.com/

**Comment by niemeyer** [comment]
Update from support:

> We think we found the problem machine and are looking for a root cause.

Seems to be working now. Might be fixed, but given that feedback we might still see a few bumps.

**Comment by niemeyer** [comment]
And it's sorted:

> We've just deployed some changes to resolve this and I can see that https://gopkg.in/mgo.v2 is now loading again. We've updated our status back to green.
>
> Sorry for the trouble this caused you and your users. Don't hesitate to follow up if you're still seeing any problems or if you have any questions.

**Comment by sysradium** [comment]
@niemeyer unfortunately the problem is back

**Comment by niemeyer** [comment]
There we go again... just got in touch with them again.

**Comment by Ads20000** [comment]
Problems have been [reflected on GitHub System Status](https://status.github.com/messages)

**Comment by andrewslotin** [comment]
It looks like the same issue is happening again. I'm currently experiencing the same behaviour while trying to install the `gometalinter.v2`:

```
$ curl https://gopkg.in/alecthomas/gometalinter.v2
Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://github.com/alecthomas/gometalinter.git/info/refs?service=git-upload-pack: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by niemeyer** [comment]
@andrewslotin Please see the last few messages above.

It also looks like it's almost sorted, from their status page:

![image](https://user-images.githubusercontent.com/378683/45367287-d1124900-b5d8-11e8-9fab-2714a810083f.png)

**Comment by Baha-sk** [comment]
GitHub issue still persisting 
https://github.com/golang/go/issues/27622 was closed but my build is still failing. 

Thanks!

**Comment by mdittmer** [comment]
Is this a special case of this issue?

```sh
go get -u gopkg.in/src-d/go-git.v4/...                     
# cd [...]/src/gopkg.in/src-d/go-git.v4; git pull --ff-only                           
remote: Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://github.com/src-d/go-git.git/info/refs?service=git-upload-pack: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
fatal: unable to access 'https://gopkg.in/src-d/go-git.v4/': The requested URL returned error: 502
package gopkg.in/src-d/go-git.v4: exit status 1
package gopkg.in/check.v1: unrecognized import path "gopkg.in/check.v1" (parse https://gopkg.in/check.v1?go-get=1: no go-import meta tags ())
package gopkg.in/src-d/go-git-fixtures.v3: unrecognized import path "gopkg.in/src-d/go-git-fixtures.v3" (parse https://gopkg.in/src-d/go-git-fixtures.v3?go-get=1: no go-import meta tags ())
```

**Comment by Baha-sk** [comment]
looks like it, it's a general Github http 502 error

**Comment by esetnik** [comment]
@niemeyer can you fail over to hot spare https://p3.gopkg.in/yaml.v2 please?

**Comment by niemeyer** [comment]
@esetnik Since this is a more general issue on GitHub and the issue comes and goes, we have no guarantees that shifting won't present the same problem. Also, GitHub is using our service to debug their outage, so I'm keen on not masking the problem for them so it can be fixed faster and for good.

Per their support:

> It looks like https://gopkg.in/mgo.v2 is accessible at the moment and our team are making use of this URL as they work to resolve the issue. I'll follow up again when I have another update for you.

We also had an update moments ago:

![image](https://user-images.githubusercontent.com/378683/45374773-045dd380-b5eb-11e8-923d-02a0f98fb1f7.png)

**Comment by adriamb** [comment]
there's any known workaround for golang module system? Like adding/modifying something in the `go.mod`?

**Comment by esetnik** [comment]
> @esetnik Since this is a more general issue on GitHub and the issue comes and goes, we have no guarantees that shifting won't present the same problem. Also, GitHub is using our service to debug their outage, so I'm keen on not masking the problem for them so it can be fixed faster and for good.
> 
> Per their support:
> 
> > It looks like https://gopkg.in/mgo.v2 is accessible at the moment and our team are making use of this URL as they work to resolve the issue. I'll follow up again when I have another update for you.
> 
> We also had an update moments ago:
> 
> ![image](https://user-images.githubusercontent.com/378683/45374773-045dd380-b5eb-11e8-923d-02a0f98fb1f7.png)

I'm not sure what's different about your connection, but I definitely cannot resolve https://gopkg.in/mgo.v2. I think it's a bit unreasonable for Github team to assume third-parties won't alter their own infrastructure to do everything they can to mitigate upstream affects of the outage for their users.

**Comment by glb** [comment]
Issue appears to be resolved from here at least! 🎉 My build just passed.

<img width="616" alt="image" src="https://user-images.githubusercontent.com/372794/45381455-5692fa80-b5d3-11e8-8e76-c0c26d13e8a5.png">

**Comment by Baha-sk** [comment]
same here... but hopefully it's not intermittent.

**Comment by sublee** [comment]
The GitHub status says everything operates normally since 6 hours ago:

![image](https://user-images.githubusercontent.com/19982/45395525-7973ec00-b671-11e8-80fa-3a08bbe7ff60.png)

When I visit http://gopkg.in/yaml.v2 in a Web browser, it works as well. But my build in Travis CI is still failing (gin-gonic depends on go-yaml in gopkg.in):

```
$ dep ensure -update github.com/hangulize/hangulize
Solving failure:
	(1) failed to list versions for https://gopkg.in/yaml.v2: remote: Not Found
fatal: repository 'https://github.com/go-yaml/yaml/' not found
: exit status 128
	(2) failed to list versions for http://gopkg.in/yaml.v2: remote: Not Found
fatal: repository 'http://github.com/go-yaml/yaml/' not found
: exit status 128
```

Is there anyone who has an idea about this experience?

**Comment by niemeyer** [comment]
Apparently they've solved the issue for good, so I'm closing this one as well.

Sorry for the trouble everyone.

**Comment by sublee** [comment]
My problem https://github.com/niemeyer/gopkg/issues/63#issuecomment-420475234 was not due to this service issue. The reason was `GIT_HTTP_USER_AGENT` customized by Travis CI's `deploy` stage. Travis CI sets it as `GIT_HTTP_USER_AGENT=travis/0.1.0 dpl/1.10.0 git/2.15.1` only in the `deploy` stage.

GitHub's git HTTPS URL without `.git`, like `https://github.com/go-yaml/yaml` rather than `https://github.com/go-yaml/yaml.git`, fails on an unexpected `User-Agent` header.

```console
$ GIT_HTTP_USER_AGENT='' go get gopkg.in/yaml.v2
# cd .; git clone <https://gopkg.in/yaml.v2> .../go/src/gopkg.in/yaml.v2
Cloning into '.../go/src/gopkg.in/yaml.v2'...
error: RPC failed; HTTP 422 curl 22 The requested URL returned error: 422 Unprocessable Entity
fatal: The remote end hung up unexpectedly
package gopkg.in/yaml.v2: exit status 128
```

**Comment by acloudiator** [comment]
Github status seems all good for today, but I encountered this issue again.

```
package gopkg.in/inf.v0: unrecognized import path "gopkg.in/inf.v0" (https fetch: Get https://gopkg.in/inf.v0?go-get=1: dial tcp 35.196.143.184:443: i/o timeout)
package gopkg.in/mgo.v2: unrecognized import path "gopkg.in/mgo.v2" (https fetch: Get https://gopkg.in/mgo.v2?go-get=1: dial tcp 35.196.143.184:443: i/o timeout)
package gopkg.in/mgo.v2/bson: unrecognized import path "gopkg.in/mgo.v2/bson" (https fetch: Get https://gopkg.in/mgo.v2/bson?go-get=1: dial tcp 35.196.143.184:443: i/o timeout)
```

**Comment by adityaalifn** [comment]
@niemeyer it is happening again

<img width="1611" alt="Screen Shot 2021-11-15 at 14 43 07" src="https://user-images.githubusercontent.com/15376478/141741614-4bf53297-90af-49cd-8604-e026b5e127b0.png">

**Comment by aagamdoshi** [comment]
Facing the below error : 
	
	remote: Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://github.com/go-yaml/yaml.git/info/refs?service=git-upload-pack: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
	
	@niemeyer

**Comment by jivot** [comment]
+1
our ci/cd jobs are failing with something similar
```
go: github.com/rubenv/sql-migrate@v0.0.0-20200616145509-8d140a17f351 requires
    gopkg.in/gorp.v1@v1.7.2: unrecognized import path "gopkg.in/gorp.v1": reading https://gopkg.in/gorp.v1?go-get=1: 502 Bad Gateway
    server response: Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://github.com/go-gorp/gorp.git/info/refs?service=git-upload-pack: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by niemeyer** [comment]
I'm looking into it. Given the multiple reports, it's of course a real issue, but it's not easy to debug it on my end as this looks like GitHub failing to respond the request on time.  If I can't find anything here, I'll reach out to GitHub and see if someone can help me.

**Comment by kulkarnisamr** [comment]
looks like it's working now

**Comment by SamuliVirtapohja** [comment]
Our ci/cd seems to pass currently.

Has there been any update/post somewhere about this?

**Comment by SamuliVirtapohja** [comment]
Success 15.11.2021 at 12:21 PM GMT +2
Success 15.11.2021 at 12:36 PM GMT +2 <- incidents happen from here on out
Failed 15.11.2021 at 12:40 PM GMT +2
Failed 15.11.2021 at 12:41 PM GMT +2 
Failed 15.11.2021 at 12:47 PM GMT +2 
Failed 15.11.2021 at 1:02 PM GMT +2 
Failed 15.11.2021 at 1:49 PM GMT +2 
Success 15.11.2021 at 2:26 PM GMT +2 
Failed 15.11.2021 at 3:06 PM GMT +2 
Success 15.11.2021 at 3:22 PM GMT +2 
Success 15.11.2021 at 4:38 PM GMT +2 
Failed 15.11.2021 at 5:00 PM GMT +2 
Failed 15.11.2021 at 5:59 PM GMT +2 <- This is the last failed run that our logs show
Success 16.11.2021 at 8:48 AM GMT +2 <- Success from here on out

There was also some issues with the pipelines for our provider at that time but this is the closest thing that I could find https://status.dev.azure.com/_event/272370766

**Comment by kulkarnisamr** [comment]
The earliest run that failed for me was around Nov 15, 2021 2:38 AM (UTC-8:00)

**Comment by niemeyer** [comment]
Thanks for the data, folks.  Still zero feedback from GitHub. My best guess at the moment is that there was some inconsistent hiccup there and it's been addressed.

For future cases, please note that any such hiccup in GitHub ends up showing up as a failure from gopkg.in itself. In such cases, though, the log will be clear about what particular operation is failing and how.

Feel free to report here anyway, though, even more if you see https://www.githubstatus.com/ and there's nothing being reported there. It's useful to get some perspective on how it's failing and where.

**Comment by niemeyer** [comment]
Some feedback from GitHub:

![image](https://user-images.githubusercontent.com/378683/142880598-30ebee13-4b70-4951-b353-56213f1d1a92.png)

**Comment by niemeyer** [comment]
Over the last few days we've also been doing some analysis with help from the IS team at Canonical, and we found that a relevant percentage of requests, which amounts to over _one million requests a day,_ is being performed by a one small for-profit organization.  We'll probably introduce a quota to encourage cases like this to be more carefully designed.

**Comment by LKay** [comment]
This is happening again... Any chance it will be resolved and gopkg.io becomes stable? IT's been happening for over 2 years randomly, as a result packages hosted on here are not reliable in production environment.

**Comment by lgosse** [comment]
Same here for about two hours

**Comment by SamuliVirtapohja** [comment]
Yup, just checking in here. Happened to us too.

**Comment by kaushiknag90** [comment]
This is happening to us as well and causing a lot of failures in our CI pipeline while downloading packages to build the binaries.
Could you please help us with a work around or a permanent fix for the same.

**Comment by co60ca** [comment]
Would replacing the problematic source with a github link instead using replace in go.mod help?

**Comment by SamuliVirtapohja** [comment]
> Would replacing the problematic source with a github link instead using replace in go.mod help?

I mean it would help but the amount of work required for a not long term solution is not realistic.

**Comment by niemeyer** [comment]
>  Could you please help us with a work around or a permanent fix for the same.

I cannot fix GitHub permanently. I cannot even fix it temporarily. The service provided by `gopkg.in` depends entirely on GitHub itself being able to serve requests. I have no visibility on how GitHub dispatches requests internally, but what I'm doing right now is adding a more strict quota on organizations that are clearly abusing the system so that we can try to make GitHub happier about the requests.

**Comment by niemeyer** [comment]
Just to confirm that this indeed the same issue, would anyone have the error message and timestamp at hand?

**Comment by SamuliVirtapohja** [comment]
Can provide them tomorrow.

**Comment by kaushiknag90** [comment]
Some of the same error message and times are below. The timestamp is in IST.
`[Container] 2021/11/25 16:01:00 
Step 14/27 : RUN go mod download

 ---> Running in c5d727371cc6

go: gopkg.in/yaml.v2@v2.3.0 requires

	gopkg.in/check.v1@v0.0.0-20161208181325-20d25e280405: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /go/pkg/mod/cache/vcs/9241c28341fcedca6a799ab7a465dd6924dc5d94044cbfabb75778817250adfc: exit status 128:

	remote: Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://github.com/go-check/check.git/info/refs?service=git-upload-pack: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

	fatal: unable to access 'https://gopkg.in/check.v1/': The requested URL returned error: 502

The command '/bin/sh -c go mod download' returned a non-zero code: 1`

`[Container] 2021/11/25 20:45:33 Running command make unit-test
go test -count=1 -covermode=atomic -coverprofile=coverage-unit.out ./...
go: bitbucket.org/swigy/xp-go-client@v0.0.0-20210728131314-2270d5ec76f6 requires
    gopkg.in/sourcemap.v1@v1.0.5: reading gopkg.in/sourcemap.v1/go.mod at revision v1.0.5: unknown revision v1.0.5
Makefile:21: recipe for target 'unit-test' failed
make: *** [unit-test] Error 1`

**Comment by kaushiknag90** [comment]
Getting this error again today while pulling dependencies from gopkg. Can you please help or suggest as this is blocking our builds

`
go: gopkg.in/check.v1@v1.0.0-20201130134442-10cb98267c6c: unrecognized import path "gopkg.in/check.v1": reading https://gopkg.in/check.v1?go-get=1: 502 Bad Gateway
Makefile:56: recipe for target 'test' failed</span></span></body></html>
`

**Comment by deydebaditya** [comment]
Getting this error again today while resolving dependencies from gopkg. This is blocking production critical builds for us. Can someone please look into this on priority?

`go: gopkg.in/alexcesaro/statsd.v2@v2.0.0: unrecognized import path "gopkg.in/alexcesaro/statsd.v2": reading https://gopkg.in/alexcesaro/statsd.v2?go-get=1: 502 Bad Gateway`

**Comment by DavidYos27** [comment]
Same issue as @kaushiknag90  
the issue persists when running go mod download: 

`gopkg.in/go-playground/assert.v1@v1.2.1: unrecognized import path "gopkg.in/go-playground/assert.v1" (parse https://gopkg.in/go-playground/assert.v1?go-get=1: no go-import meta tags ())`
`gopkg.in/yaml.v2@v2.2.2: unrecognized import path "gopkg.in/yaml.v2" (parse https://gopkg.in/yaml.v2?go-get=1: no go-import meta tags ())`

**Comment by hamdi-ben-yaflah** [comment]
Having the same issue.

`server response: Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://github.com/go-yaml/yaml.git/info/refs?service=git-upload-pack: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

**Comment by hamdi-ben-yaflah** [comment]
@DavidYos27 @ucanfil @deydebaditya @kaushiknag90 is it still happening for you guys?

**Comment by DavidYos27** [comment]
@hamdi-ben-yaflah not sure what's the root cause of the problem, but mine is resolved

**Comment by deydebaditya** [comment]
@hamdi-ben-yaflah No, still facing the sae issue.
`go: github.com/spf13/viper@v1.9.0 requires
	github.com/sagikazarmark/crypt@v0.1.0 requires
	go.etcd.io/etcd/client/v2@v2.305.0: unrecognized import path "go.etcd.io/etcd/client/v2": reading https://go.etcd.io/etcd/client/v2?go-get=1: 503 Service Unavailable`

**Comment by ucanfil** [comment]
@hamdi-ben-yaflah mine was resolved as well.

**Comment by bhushan-mdn** [comment]
Guys, it's happening again. Just linking other issues so that people know what's happening. 
[go-yaml/yaml#887](https://github.com/go-yaml/yaml/issues/887)
[srvaroa/labeler#43](https://github.com/srvaroa/labeler/issues/43)

**Comment by bhushan-mdn** [comment]
Created a discussion earlier, and based on help from @matthewgoodman13 was directed to a reddit post. Link to discussion:
https://github.com/orgs/community/discussions/29332

[DasSkelett](https://www.reddit.com/user/DasSkelett/) on the reddit post said that we could either use vendoring or GOPROXY. The GOPROXY route was a quick and easy fix for me. Just export the environment variable GOPROXY as proxy.golang.org and then run your go get command and you're good to go:
`export GOPROXY=https://proxy.golang.org`

**Comment by EvanBoyle** [comment]
Also hitting this.

**Comment by dbizari** [comment]
Hi guys, also having this issue, anyone found any solution beside trying to use GOPROXY https://proxy.golang.org ?

**Comment by eberbis** [comment]
It seems to be resolved now 👍

**Comment by misdirectedpuffin** [comment]
Looks like it's happening again:

```bash
go install github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login@latest: github.com/awslabs/amazon-ecr-credential-helper/ecr-login@none updating to
        github.com/awslabs/amazon-ecr-credential-helper/ecr-login@v0.0.0-20221027043306-dc425bc05c64 requires
        github.com/stretchr/testify@v1.8.1 requires
        gopkg.in/yaml.v3@v3.0.1: unrecognized import path "gopkg.in/yaml.v3": reading https://gopkg.in/yaml.v3?go-get=1: 502 Bad Gateway
        server response: Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://github.com/go-yaml/yaml.git/info/refs?service=git-upload-pack: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by ChenaLee** [comment]
Happening for me too.

**Comment by saadzaman** [comment]
Happening today again !

**Comment by chapmanc** [comment]
:+1: For me

**Comment by metal3d** [comment]
And now…

That's a “urgent” problem while a lot of packages are referenced through gopkg.in, and we can't work on our software (build fails while getting the dependencies)

Any change to find what's the issue? (we can help on resolution)

**Comment by metal3d** [comment]
```
go: fyne.io/fyne/v2@v2.2.3 requires
	gopkg.in/check.v1@v1.0.0-20200227125254-8fa46927fb4f: unrecognized import path "gopkg.in/check.v1": reading https://gopkg.in/check.v1?go-get=1: 502 Bad Gateway
	server response: Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://github.com/go-check/check.git/info/refs?service=git-upload-pack: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by Aerowiel** [comment]
Yup happening for me too... with gopkg.in/square/go-jose.v2
Thanks to this issue, now i know i'm not the only facing this non-sense

**Comment by misdirectedpuffin** [comment]
Is there any workaround at all for this (other than using the proxy, which doesn't seem to work)?

**Comment by saadzaman** [comment]
Adding proxy path solved the issue for meOn 4 Nov 2022 11:07 pm, Florian PENDARIES ***@***.***> wrote:
Yup happening for me too... with gopkg.in/square/go-jose.v2
Thanks to this issue, now i know i'm not the only facing this non-sense

**Comment by Aerowiel** [comment]
@saadzaman which one ?

**Comment by johnpekcan** [comment]
experiencing this as well

**Comment by misdirectedpuffin** [comment]
> Adding proxy path solved the issue for meOn 4 Nov 2022 11:07 pm, Florian PENDARIES ***@***.***> wrote: Yup happening for me too... with gopkg.in/square/go-jose.v2 Thanks to this issue, now i know i'm not the only facing this non-sense —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
```bash
[ec2-user@ip-10-180-29-71 ~]$ GOPROXY=https://proxy.golang.org sudo /usr/bin/go install github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login@latest
go install github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login@latest: github.com/awslabs/amazon-ecr-credential-helper/ecr-login@none updating to
        github.com/awslabs/amazon-ecr-credential-helper/ecr-login@v0.0.0-20221027043306-dc425bc05c64 requires
        github.com/stretchr/testify@v1.8.1 requires
        gopkg.in/yaml.v3@v3.0.1: unrecognized import path "gopkg.in/yaml.v3": reading https://gopkg.in/yaml.v3?go-get=1: 502 Bad Gateway
        server response: Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://github.com/go-yaml/yaml.git/info/refs?service=git-upload-pack: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```
Is there another proxy I should use?

**Comment by niemeyer** [comment]
Please see #78 for details on this week's issue.

**Comment by j-maltese** [comment]
@niemeyer Is the cannot talk to GitHub issue occurring again today? I'm getting a 502 when our pipelines run and "package gopkg.in/yaml.v2: exit status 128"

**Comment by j-maltese** [comment]
@niemeyer says there was a major outage this morning that is now resolved. But I am still having issues on our pipelines: https://status.canonical.com/#/incident/KNms6QK9ewuzz-7xUsPsNylV20jEt5kyKsd8A-3ptQHaFVW3sYpVjaoC6hSLL7x3PgfLD6yowK_1bYTd8bAkgg==

**Comment by jarrywangcn** [comment]
happen to me again...
